hello = hellee44
version = 2

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.19.130}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  zipkin:
    base-url: http://192.168.19.130:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0 #采样比例
