hello: hellee44
version: 2

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:101.37.202.3}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

#   zipkin:
#     base-url: http://101.37.202.3:9411
#     sender:
#       type: rabbit
  sleuth:
    sampler:
      probability: 1.0 #采样比例
